### ISSUE TITLE
Summer Missions: Details not loading

### ISSUE THREAD

**Issue by fedorareis** [CruCentralCoast/CruiOS#143]
In the Summer Missions portion, a number of the summer missions only display an image and don't have the rest of the info card. When you click on the image it still takes the user to the full information about the Summer Mission. However, it looks bad and is confusing when only 3 out of the 6 Summer Missions show the name, dates, and location on the main Summer Missions page.

**Comment by kyle-fletcher** [comment]
This is what Summer Missions looks like for me (corroborating @fedorareis). I think the image that is displaying for those summer missions is a standard filler image that should be a white background instead like the fix that happened on the Events page. And yes, the rest of the card is missing.

iOS 11.0.2
Version 1.4 (20)
iPhone 6

![img_1179](https://user-images.githubusercontent.com/5009162/31255179-64885bee-a9e0-11e7-8302-4824eacfdc4e.png)

**Comment by tydahlwave** [comment]
Like this?
![simulator screen shot - iphone 7 plus - 2017-10-07 at 16 43 26](https://user-images.githubusercontent.com/4985998/31312680-b6d222d2-ab7e-11e7-874e-f8548117b8eb.png)

**Comment by tydahlwave** [comment]
@kyle-fletcher

**Comment by kyle-fletcher** [comment]
Sorry, I wasn't very clear but you are very close. I meant that it had a standard image that it loaded for every mission trip (the lake picture), but that instead of that standard image, the white background should be standard. Kind of like removing the "Crossroads" standard picture that preloaded for every event in our event section until the correct picture loaded. So it looks like you got the white background in instead of the standard lake image, so that's good. 

The one change I would make is that for mission trips that don't have an image in the database, I think it should do what the event screen does, shrinking the white box to just fit the words, that way there isn't a bunch of blank white space above the words.

**Comment by tydahlwave** [comment]
![simulator screen shot - iphone 7 plus - 2017-10-07 at 17 42 17](https://user-images.githubusercontent.com/4985998/31312938-0f8007f2-ab87-11e7-94de-f854d22ffedb.png)
