### ISSUE TITLE
Keyboard stays up when editing & switching fields on Offer Ride screen

### ISSUE THREAD

**Issue by esolum** [CruCentralCoast/CruiOS#38]
Jon did this. Possibly after trying to select a pickup location. Quitting the app is the only thing that gets rid of the keyboard.

**Comment by kyle-fletcher** [comment]
This is still an issue that is present. Basically, if you are trying to edit a selection that requires text input, then the keyboard pops up. The natural thing to do is to click the next area of the questionnaire to fill out...but in doing so, the keyboard stays up regardless of whether that new input area needs a keyboard. Once in that new area that doesn't need a keyboard, you cannot close the keyboard unless you go back to a input area that is text based. So for instance, if you type in your name and then press the area to type in your phone number, the keyboard stays up. we don't see the issue here because both need the keyboard. But as soon as you move from the phone number to the event, the keyboard will not go away unless you go back to phone number.  

Version: iOS 10 running Beta 1.4
Phone: iPhone 6

![img_1133](https://user-images.githubusercontent.com/5009162/29899873-d3ecce0c-8da2-11e7-8b85-e81134094465.PNG)
